import pandas as pd
import numpy as np

waste_fraction_defaults = {'Australia and New Zealand' : [0.259, 0.122, 0.065, 0.12, 0.029, 0.083, 0.018, 0.028, 0.0, 0.276, 1.0000001],
                            'Caribbean' : [0.469, 0.0000001, 0.024, 0.17, 0.051, 0.099, 0.05, 0.057, 0.019, 0.035, 0.9740001],
                            'Central America' : [0.627, 0, 0.003, 0.126, 0.022, 0.103, 0.027, 0.033, 0, 0.06, 1.001],
                            'Eastern Africa' : [0.444, 0.069, 0.005, 0.104, 0.03, 0.08, 0.026, 0.021, 0.004, 0.217, 1],
                            'Eastern Asia' : [0.403, 0, 0.021, 0.204, 0.01, 0.065, 0.027, 0.043, 0, 0.229, 1.002],
                            'Eastern Europe' : [0.318, 0.024, 0.025, 0.171, 0.031, 0.046, 0.007, 0.018, 0.005, 0.354, 0.999],
                            'Middle Africa' : [0.284, 0, 0, 0.08, 0.013, 0.071, 0.014, 0.011, 0.0000001, 0.527, 1.0000001],
                            "North America" : [0.202, 0.068, 0.041, 0.233, 0.039, 0.158, 0.064, 0.042, 0.016, 0.14, 1.003],
                            "Northern Africa" : [0.504, 0, 0, 0.121, 0.058, 0.138, 0.044, 0.033, 0.0000001, 0.105, 1.0030001],
                            "Northern Europe" : [0.303, 0.052, 0.018, 0.138, 0.032, 0.049, 0.014, 0.043, 0, 0.352, 1.001],
                            "Rest of Oceania" : [0.675, 0.0000001, 0.025, 0.06, 0.0000001, 0.0000001, 0.0000001, 0.0000001, 0.0000001, 0.0000001, 0.7600007],
                            "South America" : [0.541, 0.033, 0, 0.124, 0.017, 0.137, 0.02, 0.03, 0.006, 0.091, 0.999],
                            "Central Asia" : [0.3, 0.014, 0.025, 0.247, 0.035, 0.084, 0.008, 0.059, 0, 0.23, 1.002],
                            "South-Eastern Asia" : [0.499, 0.01, 0.008, 0.112, 0.004, 0.102, 0.042, 0.037, 0, 0.186, 1],
                            "Southern Africa" : [0.24, 0, 0, 0.145, 0.055, 0.265, 0.065, 0.09, 0, 0.14, 1],
                            "Southern Europe" : [0.358, 0.014, 0.012, 0.214, 0.028, 0.141, 0.02, 0.035, 0.002, 0.178, 1.002],
                            "Western Africa" : [0.539, 0, 0, 0.075, 0.019, 0.064, 0.027, 0.013, 0, 0.265, 1.002],
                            "Western Asia" : [0.422, 0.032, 0.008, 0.153, 0.03, 0.172, 0.025, 0.034, 0.003, 0.122, 1.001],
                            "Western Europe" : [0.332, 0.027, 0.023, 0.172, 0.059, 0.205, 0.015, 0.014, 0, 0.153, 1],
                            "Southern Asia" : [0.661, 0, 0, 0.092, 0.012, 0.07, 0.009, 0.015, 0.004, 0.139, 1.002]}

waste_fraction_defaults = pd.DataFrame(waste_fraction_defaults).T
waste_fraction_defaults.columns = ['food', 'green', 'wood', 'paper_cardboard', 'textiles', 'plastic', 'metal', 'glass', 'rubber', 'other', 'total']
waste_fraction_defaults = waste_fraction_defaults.drop('total', axis=1)
#waste_fraction_defaults.head()
#waste_fraction_defaults = waste_fraction_defaults.T.to_dict()

region_lookup = {'China': 'Eastern Asia',
                 'Japan': 'Eastern Asia',
                 'Republic of Korea': 'Eastern Asia',
                 'Mongolia': 'Central Asia',
                 'Democratic People\'s Republic of Korea': 'Eastern Asia',
                 'Bangladesh': 'Southern Asia',
                 'India': 'Southern Asia',
                 'Nepal': 'Southern Asia',
                 'Sri Lanka': 'Southern Asia',
                 'Pakistan': 'Southern Asia',
                 'Brunei Darussalam': 'South-Eastern Asia',
                 'Cambodia': 'South-Eastern Asia',
                 'Indonesia': 'South-Eastern Asia',
                 'Lao People\'s Democratic Republic': 'South-Eastern Asia',
                 'Malaysia': 'South-Eastern Asia',
                 'Myanmar': 'South-Eastern Asia',
                 'Philippines': 'South-Eastern Asia',
                 'Singapore': 'South-Eastern Asia',
                 'Thailand': 'South-Eastern Asia',
                 'Vietnam ': 'South-Eastern Asia',
                 'Afghanistan': 'Central Asia',
                 'Kazakhstan': 'Central Asia',
                 'Tajikistan': 'Central Asia',
                 'Turkmenistan': 'Central Asia',
                 'Kyrgyzstan': 'Central Asia',
                 'Uzbekistan': 'Central Asia',
                 'Armenia': 'Western Asia',
                 'Georgia': 'Western Asia',
                 'Azerbaijan': 'Western Asia',
                 'Saudi Arabia': 'Western Asia',
                 'Iran': 'Western Asia',
                 'Iraq': 'Western Asia',
                 'Syrian Arab Republic': 'Western Asia',
                 'Lebanon': 'Western Asia',
                 'Israel': 'Western Asia',
                 'Kuwait': 'Western Asia',
                 'Jordan': 'Western Asia',
                 'Yemen': 'Western Asia',
                 'Oman': 'Western Asia',
                 'United Arab Emirates': 'Western Asia',
                 'Qatar': 'Western Asia',
                 'Bahrain': 'Western Asia',
                 'Egypt': 'Northern Africa',
                 'Libya': 'Northern Africa',
                 'Tunisia': 'Northern Africa',
                 'Algeria': 'Northern Africa',
                 'Morocco': 'Northern Africa',
                 'Sudan': 'Northern Africa',
                 'South Sudan': 'Northern Africa',
                 'Western Sahara': 'Northern Africa',
                 'Eritrea': 'Eastern Africa',
                 'Ethiopia': 'Eastern Africa',
                 'Somalia': 'Eastern Africa',
                 'Djibouti': 'Eastern Africa',
                 'Uganda': 'Eastern Africa',
                 'Kenya': 'Eastern Africa',
                 'Rwanda': 'Eastern Africa',
                 'Burundi': 'Eastern Africa',
                 'Tanzaia': 'Eastern Africa',
                 'Mauritanina': 'Western Africa',
                 'Senegal': 'Western Africa',
                 'The Gambia': 'Western Africa',
                 'Guinne-Bissau': 'Western Africa',
                 'Guinea': 'Western Africa',
                 'Sierra Leone': 'Western Africa',
                 'Liberia': 'Western Africa',
                 'Cote d\'Ivoire': 'Western Africa',
                 'Ghana': 'Western Africa',
                 'Togo': 'Western Africa',
                 'Benin': 'Western Africa',
                 'Nigeria': 'Western Africa',
                 'Mali': 'Middle Africa',
                 'Burkina Faso': 'Middle Africa',
                 'Niger': 'Middle Africa',
                 'Chad': 'Middle Africa',
                 'Central African Republic': 'Middle Africa',
                 'Cameroon': 'Middle Africa',
                 'Republic of Congo': 'Middle Africa',
                 'Democratic Republic of Congo': 'Middle Africa',
                 'Angola': 'Middle Africa',
                 'Zambia': 'Middle Africa',
                 'Gabon': 'Middle Africa',
                 'Malawi': 'Middle Africa',
                 'Namibia': 'Southern Africa',
                 'Botswana': 'Southern Africa',
                 'Zimbabwe': 'Southern Africa',
                 'Mozambique': 'Southern Africa',
                 'Madagascar': 'Southern Africa',
                 'South Africa': 'Southern Africa',
                 'Lesotho': 'Southern Africa',
                 'Eswatini': 'Southern Africa',
                 'Comoros': 'Southern Africa',
                 'Bulgaria': 'Eastern Europe',
                 'Croatioa': 'Eastern Europe',
                 'Serbia': 'Eastern Europe',
                 'Montenegro': 'Eastern Europe',
                 'Kosovo': 'Eastern Europe',
                 'Bosnia and Herzegovina': 'Eastern Europe',
                 'Albania': 'Eastern Europe',
                 'Czechia': 'Eastern Europe',
                 'Slovakia': 'Eastern Europe',
                 'Slovenia': 'Eastern Europe',
                 'Romania': 'Eastern Europe',
                 'Russian Federation': 'Eastern Europe',
                 'Ukraine': 'Eastern Europe',
                 'Belarus': 'Eastern Europe',
                 'Latvia': 'Eastern Europe',
                 'Lithuania': 'Eastern Europe',
                 'Estonia': 'Eastern Europe',
                 'Poland': 'Eastern Europe',
                 'Hungary': 'Eastern Europe',
                 'Republic of Moldova': 'Eastern Europe',
                 'Denmark': 'Northern Europe',
                 'Finland': 'Northern Europe',
                 'Sweden': 'Northern Europe',
                 'Norway': 'Northern Europe',
                 'Iceland': 'Northern Europe',
                 'Cyprus': 'Southern Europe',
                 'Greece': 'Southern Europe',
                 'Italy': 'Southern Europe',
                 'Malta': 'Southern Europe',
                 'Spain': 'Southern Europe',
                 'Portugal': 'Southern Europe',
                 'Turkey': 'Southern Europe',
                 'Austria': 'Western Europe',
                 'Belgium': 'Western Europe',
                 'Netherlands': 'Western Europe',
                 'France': 'Western Europe',
                 'Germany': 'Western Europe',
                 'Ireland': 'Western Europe',
                 'Luxembourg': 'Western Europe',
                 'Switzerland': 'Western Europe',
                 'United Kingdom': 'Western Europe',
                 'Bahamas': 'Caribbean',
                 'Cuba': 'Caribbean',
                 'Dominican Republic': 'Caribbean',
                 'St. Lucia': 'Caribbean',
                 'Costa Rica': 'Central America',
                 'Guatemala': 'Central America',
                 'Hondruas': 'Central America',
                 'Nicarauga': 'Central America',
                 'Belize': 'Central America',
                 'Panama': 'Central America',
                 'El Salvador': 'Central America',
                 'Argentina': 'South America',
                 'Bolivia': 'South America',
                 'Brazil': 'South America',
                 'Chile': 'South America',
                 'Colombia': 'South America',
                 'Ecuador': 'South America',
                 'Paraguay': 'South America',
                 'Peru': 'South America',
                 'Uruguay': 'South America',
                 'Venezuela': 'South America',
                 'Canada': 'North America',
                 'Mexico': 'North America',
                 'United States of America': 'North America',
                 'American Samoa': 'North America',
                 'Australia': 'Australia and New Zealand',
                 'New Zealand': 'Australia and New Zealand',
                 'Fiji': 'Rest of Oceania',
                 'Papua New Guinea': 'Rest of Oceania',
                 'Bhutan': 'Southern Asia',
                 'Côte d’Ivoire': 'Western Africa',
                 'Ivory Coast': 'Western Africa',
                 'Congo, Dem. Rep.': 'Middle Africa',
                 'Congo, Rep.': 'Middle Africa',
                 'Czech Republic': 'Eastern Europe',
                 'Egypt, Arab Rep.': 'Northern Africa',
                 'Micronesia, Fed. Sts.': 'Rest of Oceania',
                 'Gambia, The': 'Western Africa',
                 'Equatorial Guinea': 'Middle Africa',
                 'Honduras': 'Central America',
                 'Croatia': 'Eastern Europe',
                 'Haiti': 'Caribbean',
                 'Isle of Man': 'Western Europe',
                 'Iran, Islamic Rep.': 'Western Asia',
                 'Kyrgyz Republic': 'Central Asia',
                 'Kiribati': 'Rest of Oceania',
                 'Korea, Rep.': 'Eastern Asia',
                 'Lao PDR': 'South-Eastern Asia',
                 'Moldova': 'Eastern Europe',
                 'Maldives': 'Southern Asia',
                 'Marshall Islands': 'Rest of Oceania',
                 'Macedonia, FYR': 'Eastern Europe',
                 'Northern Mariana Islands': 'Rest of Oceania',
                 'Mauritania': 'Western Africa',
                 'Nicaragua': 'Central America',
                 'Palau': 'Rest of Oceania',
                 'West Bank and Gaza': 'Western Asia',
                 'Solomon Islands': 'Rest of Oceania',
                 'Slovak Republic': 'Eastern Europe',
                 'Timor-Leste': 'South-Eastern Asia',
                 'Tonga': 'Rest of Oceania',
                 'Tuvalu': 'Rest of Oceania',
                 'Tanzania': 'Eastern Africa',
                 'United States': 'North America',
                 'Venezuela, RB': 'South America',
                 'Vietnam': 'South-Eastern Asia',
                 'Vanuatu': 'Rest of Oceania',
                 'Samoa': 'Rest of Oceania',
                 'Yemen, Rep.': 'Western Asia',
                 'Democratic Republic of the Congo': 'Middle Africa',
                 'DRC': 'Middle Africa',
                 'Micronesia': 'Rest of Oceania',
                 'Gambia': 'Western Africa',
                 'Macedonia': 'Eastern Europe',
                 'Mongolia ': 'Central Asia',
                 'Viet Nam': 'South-Eastern Asia',
                }


msw_per_capita_defaults = {
    'Australia and New Zealand' : 0.6,
    'Caribbean' : 0.78,
    'Central America' : 0.58,
    'Central Asia' : 0.34,
    'Eastern Africa' : 0.29,
    'Eastern Asia' : 0.48,
    'Eastern Europe' : 0.37,
    'Middle Africa' : 0.19,
    'North America' : 0.96,
    "Northern Africa" : 0.41,
    "Northern Europe" : 0.48,
    "Rest of Oceania" : (1.18 + 1.35)/2,
    "South America" : 0.43,
    "South-Eastern Asia" : 0.46,
    "Southern Africa" : 0.33,
    "Southern Asia" : 0.5,
    "Southern Europe" : 0.47,
    "Western Africa" : 0.18,
    "Western Asia" : 0.69,
    "Western Europe" : 0.59
}
msw_per_capita_defaults = {key: (value / 365) * 1000 for key, value in msw_per_capita_defaults.items()} # convert from tons/year to kg/day

msw_per_capita_country = {
    'Tajikistan': 0.32,
    'Turkmenistan': 0.36,
    'China': 0.37,
    'Japan': 0.35,
    'Mongolia': 0.24,
    'Republic of Korea': 0.35,
    'Brunei Darussalam': 0.32,
    'Lao PDR': 0.26,
    'Malaysia': 0.55,
    'Myanmar': 0.16,
    'Philippines': 0.18,
    'Singapore': 1.28,
    'Thailand': 0.64,
    'Viet Nam': 0.53,
    'Bangladesh': 0.18,
    'Bhutan': 0.53,
    'India': 0.12,
    'Iran': 0.06,
    'Maldives': 0.91,
    'Nepal': 0.04,
    'Pakistan': 0.31,
    'Sri Lanka': 1.86,
    'Armenia': 0.25,
    'Bahrain': 0.4,
    'Cyprus': 0.69,
    'Georgia': 0.62,
    'Israel': 0.62,
    'Jordan': 0.38,
    'Kuwait': 3.05,
    'Lebanon': 0.43,
    'Oman': 0.26,
    'Qatar': 1.25,
    'Saudi Arabia': 0.47,
    'Palestine': 0.38,
    'Syrian Arab Republic': 0.50,
    'Turkey': 0.41,
    'United Arab Emirates': 0.61,
    'Algeria': 0.44,
    'Egypt': 0.5,
    'Morocco': 0.53,
    'Sudan': 0.29,
    'Tunisia': 0.30,
    'Burundi': 0.20,
    'Comoros': 0.81,
    'Eritrea': 0.18,
    'Ethiopia': 0.11,
    'Kenya': 0.11,
    'Madagascar': 0.29,
    'Malawi': 0.18,
    'Mauritius': 0.31,
    'Mozambique': 0.05,
    'Reunion': 0.69,
    'Rwanda': 0.19,
    'Seychelles': 1.09,
    'Uganda': 0.12,
    'United Republic of Tanzania': 0.09,
    'Zambia': 0.08,
    'Zimbabwe': 0.19,
    'Angola': 0.18,
    'Cameroon': 0.28,
    'Central African Republic': 0.18,
    'Chad': 0.18,
    'Congo': 0.18,
    'Democratic Republic of the Congo': 0.18,
    'Gabon': 0.16,
    'Sao Tome and Principe': 0.18,
    'Botswana': 0.38,
    'Lesotho': 0.18,
    'Namibia': 0.18,
    'South Africa': 0.73,
    'Swaziland': 0.19,
    'Benin': 0.20,
    'Burkina Faso': 0.19,
    'Cape Verde': 0.18,
    'Cote d\'Ivoire': 0.18,
    'Gambia': 0.19,
    'Ghana': 0.03,
    'Mali': 0.24,
    'Mauritania': 0.18,
    'Niger': 0.18,
    'Nigeria': 0.20,
    'Senegal': 0.19,
    'Sierra Leone': 0.16,
    'Togo': 0.19,
    'Belarus': 0.38,
    'Bulgaria': 0.55,
    'Czechia': 0.32,
    'Hungary': 0.40,
    'Poland': 0.32,
    'Romania': 0.31,
    'Russian Federation': 0.34,
    'Slovakia': 0.32,
    'Denmark': 0.76,
    'Estonia': 0.31,
    'Finland': 0.47,
    'Iceland': 0.48,
    'Ireland': 0.62,
    'Latvia': 0.32,
    'Lithuania': 0.40,
    'Norway': 0.47,
    'Sweden': 0.44,
    'United Kingdom': 0.51,
    'Bosnia and Herzegovina': 0.33,
    'Croatia': 0.38,
    'Greece': 0.53,
    'Italy': 0.55,
    'Malta': 0.6,
    'Montenegro': 0.54,
    'Portugal': 0.52,
    'Serbia': 0.36,
    'Slovenia': 0.49,
    'Spain': 0.51,
    'Macedonia': 0.35,
    'Austria': 0.56,
    'Belgium': 0.46,
    'France': 0.53,
    'Germany': 0.60,
    'Luxembourg': 0.68,
    'Netherlands': 0.57,
    'Switzerland': 0.71,
    'Anguilla': 1.10,
    'Antigua and Barbuda': 1.39,
    'Bahamas': 1.19,
    'Barbados': 1.73,
    'Cuba': 0.3,
    'Dominica': 0.32,
    'Dominican Republic': 0.43,
    'Grenada': 0.99,
    'Guadeloupe': 0.60,
    'Haiti': 0.37,
    'Jamaica': 0.07,
    'Saint Kitts and Nevis': 1.99,
    'Saint Lucia': 0.25,
    'Saint Vincent and the Grenadines': 0.35,
    'Trinidad and Tobago': 0.58,
    'Belize': 1.05,
    'Costa Rica': 0.5,
    'El Salvador': 0.41,
    'Guatemala': 0.73,
    'Honduras': 0.53,
    'Mexico': 0.34,
    'Nicaragua': 0.4,
    'Panama': 0.44,
    'Argentina': 0.37,
    'Bolivia': 0.12,
    'Brazil': 0.31,
    'Chile': 0.35,
    'Colombia': 0.35,
    'Ecuador': 0.41,
    'French Guiana': 0.37,
    'Guyana': 1.95,
    'Paraguay': 0.08,
    'Peru': 0.37,
    'Suriname': 0.50,
    'Uruguay': 0.04,
    'Venezuela': 0.42,
    'Bermuda': 1.3,
    'Canada': 0.85,
    'United States of America': 0.74,
    'Australia': 0.61,
    'New Zealand': 0.58,
    'Fiji': 0.77,
    'Solomon Islands': 1.57,
    'Vanuatu': 1.2,
    'Tonga': 1.35
}
msw_per_capita_country = {key: (value / 365) * 1000 for key, value in msw_per_capita_country.items()} # convert from tons/year to kg/day

msw_per_capita_city = {
    'Hong Kong' : 0.93,
    'Macao' : 0.62
}
msw_per_capita_city = {key: (value / 365) * 1000 for key, value in msw_per_capita_city.items()} # convert from tons/year to kg/day


k_defaults = {'Dry':            {'food': .1,  'diapers': .1,  'green': .05, 'paper_cardboard': .02,  'textiles': .02,  'wood': .01,  'rubber': .01},
              'Moderately Dry': {'food': .18, 'diapers': .18, 'green': .09, 'paper_cardboard': .036, 'textiles': .036, 'wood': .018, 'rubber': .018},
              'Moderately Wet': {'food': .26, 'diapers': .26, 'green': .12, 'paper_cardboard': .048, 'textiles': .048, 'wood': .024, 'rubber': .024},
              'Wet':            {'food': .34, 'diapers': .34, 'green': .15, 'paper_cardboard': .06,  'textiles': .06,  'wood': .03,  'rubber': .03},
              'Very Wet':       {'food': .4,  'diapers': .4,  'green': .17, 'paper_cardboard': .07,  'textiles': .07,  'wood': .035, 'rubber': .035}
             }

#k_defaults = pd.DataFrame(k_defaults).T

# Function to get precipitation zone from annual rainfall
def get_precipitation_zone(rainfall):
    # Unit is mm
    if rainfall < 500:
        return "Dry"
    elif rainfall < 1000:
        return "Moderately Dry"
    elif rainfall < 1500:
        return "Moderately Wet"
    elif rainfall < 2000:
        return "Wet"
    else:
        return "Very Wet"
    
L_0 = {'food': 70, 'diapers': 112, 'green': 93, 'paper_cardboard': 186, 
       'textiles': 112, 'wood': 200, 'rubber': 100}

oxidation_factor = {'with_lfg':{'landfill': 0.22, 'controlled_dumpsite': 0.1, 
                                'dumpsite': 0, 'remediated_to_landfill': 0.18}, 
                    'without_lfg':{'landfill': 0.1, 'controlled_dumpsite': 0.05, 
                                   'dumpsite': 0, 'remediated_to_landfill': 0.1}}

#mef_compost = 0.005876238822222 # Unit is Mg CO2e/Mg of organic waste, wtf
mef_anaerobic = 0.26/1000*1.1023 # Unit is Mg CH4/Mg organic waste...wtf 
ch4_to_co2e = 28

gas_capture_efficiency = {'landfill': 0.6, 'controlled_dumpsite': 0.45, 'dumpsite': 0}

landfill_default_regions = set(['Eastern Asia', 'Eastern Europe', 'North America', 'Northern Europe', 'Southern Europe', 'Western Europe'])

# These numbers are kind of weird. I think...
# Does this mean...waste that isn't diverted? But also is landfilled, as opposed to untracked?
# These are from IPCC, regions are slightly weird....SWEET has Central and Southern Asia, IPCC has south central and western...using south central for western here. 
# Africa is a single average and rest of oceania is from aus/nz

fraction_open_dumped = {
    'Australia and New Zealand' : 0.0,
    'Caribbean' : 0.03,
    'Central America' : 0.13,
    'Eastern Africa' : 0.98,
    'Eastern Asia' : 0.0,
    'Eastern Europe' : 0.0,
    'Middle Africa' : 0.95,
    "North America" : 0.0,
    "Northern Africa" : 0.79,
    "Northern Europe" : 0.0,
    "Rest of Oceania" : np.nan,
    "South America" : 0.43,
    "Central Asia" : np.nan,
    "South-Eastern Asia" : np.nan,
    "Southern Africa" : np.nan,
    "Southern Europe" : 0.0,
    "Western Africa" : 0.0,
    "Western Asia" : 0.11,
    "Western Europe" : 0.0,
    "Southern Asia" : np.nan
}

fraction_to_swds = {
    'Australia and New Zealand' : 0.69,
    'Caribbean' : 0.78,
    'Central America' : 0.62,
    'Eastern Africa' : 0.0,
    'Eastern Asia' : 0.23,
    'Eastern Europe' : 0.71,
    'Middle Africa' : 0.0,
    "North America" : 0.22,
    "Northern Africa" : 0.17,
    "Northern Europe" : 0.47,
    "Rest of Oceania" : np.nan,
    "South America" : 0.40,
    "Central Asia" : np.nan,
    "South-Eastern Asia" : np.nan,
    "Southern Africa" : np.nan,
    "Southern Europe" : 0.76,
    "Western Africa" : 0.64,
    "Western Asia" : 0.68,
    "Western Europe" : 0.08,
    "Southern Asia" : np.nan
}

fraction_incinerated = {
    'Australia and New Zealand' : 0.04,
    'Caribbean' : 0.0,
    'Central America' : 0.0,
    'Eastern Africa' : 0.0,
    'Eastern Asia' : 0.24,
    'Eastern Europe' : 0.06,
    'Middle Africa' : 0.0,
    "North America" : 0.26,
    "Northern Africa" : 0.0,
    "Northern Europe" : 0.20,
    "Rest of Oceania" : np.nan,
    "South America" : 0.0,
    "Central Asia" : np.nan,
    "South-Eastern Asia" : np.nan,
    "Southern Africa" : np.nan,
    "Southern Europe" : 0.04,
    "Western Africa" : 0.0,
    "Western Asia" : 0.08,
    "Western Europe" : 0.40,
    "Southern Asia" : np.nan
}

fraction_composted = {
    'Australia and New Zealand' : 0.0,
    'Caribbean' : 0.01,
    'Central America' : 0.0,
    'Eastern Africa' : 0.01,
    'Eastern Asia' : 0.0,
    'Eastern Europe' : 0.04,
    'Middle Africa' : 0.0,
    "North America" : 0.13,
    "Northern Africa" : 0.0,
    "Northern Europe" : 0.09,
    "Rest of Oceania" : 0.0,
    "South America" : 0.0,
    "Central Asia" : np.nan,
    "South-Eastern Asia" : np.nan,
    "Southern Africa" : np.nan,
    "Southern Europe" : 0.03,
    "Western Africa" : 0.0,
    "Western Asia" : 0.01,
    "Western Europe" : 0.21,
    "Southern Asia" : np.nan
}

# Includes recycling...sometimes, seems like junk. Also, don't try adding this stuff to 100. 
fraction_unspecified = {
    'Australia and New Zealand' : 0.27,
    'Caribbean' : 0.18,
    'Central America' : 0.25,
    'Eastern Africa' : 0.01,
    'Eastern Asia' : 0.52,
    'Eastern Europe' : 0.19,
    'Middle Africa' : 0.05,
    "North America" : 0.38,
    "Northern Africa" : 0.04,
    "Northern Europe" : 0.24,
    "Rest of Oceania" : np.nan,
    "South America" : 0.18,
    "Central Asia" : np.nan,
    "South-Eastern Asia" : np.nan,
    "Southern Africa" : np.nan,
    "Southern Europe" : 0.17,
    "Western Africa" : 0.36,
    "Western Asia" : 0.12,
    "Western Europe" : 0.31,
    "Southern Asia" : np.nan
}

